services:
  backend:
    container_name: lyrics-ide-backend
    restart: always
    build: .
    ports:
      - 0.0.0.0:20240:80
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 0.0.0.0:27017:27017
