"""add owner user id

Revision ID: 0f3211e971fe
Revises: d9414be73952
Create Date: 2024-03-24 00:30:38.152071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3211e971fe'
down_revision = 'd9414be73952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('owner_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['owner_user_id'], ['user_id'])
    op.add_column('project_grant', sa.Column('grant_code_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_project_grant_grant_code_id'), 'project_grant', ['grant_code_id'], unique=False)
    op.drop_index('ix_project_grant_code_grant_code_id', table_name='project_grant_code')
    op.create_index(op.f('ix_project_grant_code_grant_code_id'), 'project_grant_code', ['grant_code_id'], unique=True)
    op.create_foreign_key(None, 'project_grant', 'project_grant_code', ['grant_code_id'], ['grant_code_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_grant_code_grant_code_id'), table_name='project_grant_code')
    op.create_index('ix_project_grant_code_grant_code_id', 'project_grant_code', ['grant_code_id'], unique=False)
    op.drop_constraint(None, 'project_grant', type_='foreignkey')
    op.drop_index(op.f('ix_project_grant_grant_code_id'), table_name='project_grant')
    op.drop_column('project_grant', 'grant_code_id')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'owner_user_id')
    # ### end Alembic commands ###
