"""nullable false for level and code

Revision ID: 1170617d3960
Revises: 0f3211e971fe
Create Date: 2024-03-24 03:09:07.468724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1170617d3960'
down_revision = '0f3211e971fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_grant', 'grant_code_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('project_grant', 'level',
               existing_type=postgresql.ENUM('OWNER', 'READ_WRITE', 'READ_ONLY', name='grantlevel'),
               nullable=False)
    op.alter_column('project_grant_code', 'level',
               existing_type=postgresql.ENUM('OWNER', 'READ_WRITE', 'READ_ONLY', name='grantlevel'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_grant_code', 'level',
               existing_type=postgresql.ENUM('OWNER', 'READ_WRITE', 'READ_ONLY', name='grantlevel'),
               nullable=True)
    op.alter_column('project_grant', 'level',
               existing_type=postgresql.ENUM('OWNER', 'READ_WRITE', 'READ_ONLY', name='grantlevel'),
               nullable=True)
    op.alter_column('project_grant', 'grant_code_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
