"""init

Revision ID: 20141e8b222b
Revises: 
Create Date: 2024-01-21 21:51:49.959302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20141e8b222b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_auth_code',
    sa.Column('auth_code_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('auth_code', sa.String(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('auth_code_id')
    )
    op.create_index(op.f('ix_email_auth_code_auth_code_id'), 'email_auth_code', ['auth_code_id'], unique=False)
    op.create_index(op.f('ix_email_auth_code_email'), 'email_auth_code', ['email'], unique=False)
    op.create_table('project',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_project_project_id'), 'project', ['project_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('music',
    sa.Column('music_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('custom_bpm', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('music_id')
    )
    op.create_index(op.f('ix_music_music_id'), 'music', ['music_id'], unique=False)
    op.create_index(op.f('ix_music_project_id'), 'music', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_music_project_id'), table_name='music')
    op.drop_index(op.f('ix_music_music_id'), table_name='music')
    op.drop_table('music')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_project_project_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_email_auth_code_email'), table_name='email_auth_code')
    op.drop_index(op.f('ix_email_auth_code_auth_code_id'), table_name='email_auth_code')
    op.drop_table('email_auth_code')
    # ### end Alembic commands ###
