"""optional bpm

Revision ID: 3272f5c22730
Revises: 99d0ee737810
Create Date: 2024-01-26 18:27:05.326125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3272f5c22730'
down_revision = '99d0ee737810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'bpm',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'bpm',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
