"""add updated_at for project

Revision ID: 66cc1260c9c2
Revises: bf5af2fe4765
Create Date: 2024-03-16 23:06:49.490415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cc1260c9c2'
down_revision = 'bf5af2fe4765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'updated_at')
    # ### end Alembic commands ###
