"""add text model

Revision ID: 67ebf262ad8c
Revises: a9cdc1e2729e
Create Date: 2024-01-21 23:57:16.228578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ebf262ad8c'
down_revision = 'a9cdc1e2729e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text',
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('text_id')
    )
    op.create_index(op.f('ix_text_project_id'), 'text', ['project_id'], unique=False)
    op.create_index(op.f('ix_text_text_id'), 'text', ['text_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_text_id'), table_name='text')
    op.drop_index(op.f('ix_text_project_id'), table_name='text')
    op.drop_table('text')
    # ### end Alembic commands ###
