"""word_meaning

Revision ID: 6e8d60461d89
Revises: c55aeb86b034
Create Date: 2024-01-27 19:37:30.650531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8d60461d89'
down_revision = 'c55aeb86b034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_meaning',
    sa.Column('word_meaning_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.Column('first_character', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('word_meaning_id')
    )
    op.create_index(op.f('ix_word_meaning_word'), 'word_meaning', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_meaning_word'), table_name='word_meaning')
    op.drop_table('word_meaning')
    # ### end Alembic commands ###
