"""add project grant

Revision ID: 7b96302bf5d3
Revises: de98df6c76fe
Create Date: 2024-03-17 01:50:32.645318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b96302bf5d3'
down_revision = 'de98df6c76fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_grant',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_index(op.f('ix_project_grant_project_id'), 'project_grant', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_grant_user_id'), 'project_grant', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_grant_user_id'), table_name='project_grant')
    op.drop_index(op.f('ix_project_grant_project_id'), table_name='project_grant')
    op.drop_table('project_grant')
    # ### end Alembic commands ###
