"""optional custom bpm

Revision ID: a9cdc1e2729e
Revises: 20141e8b222b
Create Date: 2024-01-21 21:54:37.564864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cdc1e2729e'
down_revision = '20141e8b222b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'custom_bpm',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'custom_bpm',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
