"""add project grant code

Revision ID: bad27ab62c07
Revises: 7b96302bf5d3
Create Date: 2024-03-17 15:21:41.004787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad27ab62c07'
down_revision = '7b96302bf5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_grant_code',
    sa.Column('grant_code_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('issuer_user_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('OWNER', 'READ_WRITE', 'READ_ONLY', name='grantlevel'), nullable=True),
    sa.Column('max_activations', sa.Integer(), nullable=False),
    sa.Column('current_activations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('grant_code_id', 'project_id', 'issuer_user_id')
    )
    op.create_index(op.f('ix_project_grant_code_grant_code_id'), 'project_grant_code', ['grant_code_id'], unique=False)
    op.create_index(op.f('ix_project_grant_code_issuer_user_id'), 'project_grant_code', ['issuer_user_id'], unique=False)
    op.create_index(op.f('ix_project_grant_code_project_id'), 'project_grant_code', ['project_id'], unique=False)
    op.add_column('project_grant', sa.Column('level', sa.Enum('OWNER', 'READ_WRITE', 'READ_ONLY', name='grantlevel'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_grant', 'level')
    op.drop_index(op.f('ix_project_grant_code_project_id'), table_name='project_grant_code')
    op.drop_index(op.f('ix_project_grant_code_issuer_user_id'), table_name='project_grant_code')
    op.drop_index(op.f('ix_project_grant_code_grant_code_id'), table_name='project_grant_code')
    op.drop_table('project_grant_code')
    # ### end Alembic commands ###
