"""add created_at for project

Revision ID: bf5af2fe4765
Revises: 1d0defd3744e
Create Date: 2024-03-16 22:05:43.870328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5af2fe4765'
down_revision = '1d0defd3744e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'created_at')
    # ### end Alembic commands ###
