"""add gc is_active

Revision ID: d9414be73952
Revises: bad27ab62c07
Create Date: 2024-03-17 15:34:37.954444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9414be73952'
down_revision = 'bad27ab62c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_grant_code', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_grant_code', 'is_active')
    # ### end Alembic commands ###
