"""add (updated|created)_at for text

Revision ID: de98df6c76fe
Revises: 66cc1260c9c2
Create Date: 2024-03-16 23:41:14.506572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de98df6c76fe'
down_revision = '66cc1260c9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('text', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'updated_at')
    op.drop_column('text', 'created_at')
    # ### end Alembic commands ###
