auth:
  database: lyrics
  username: lyrics
  enablePostgresUser: true

metrics:
  enabled: true

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1512Mi
    cpu: 1500m

primary:
  persistence:
    size: 5Gi

replication:
  enabled: false

architecture: standalone
