apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lyrics-ide
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: samplec0de/lyrics-ide-backend:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: backend-secret
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 20
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 80
          initialDelaySeconds: 75
          timeoutSeconds: 20
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
      imagePullSecrets:
      - name: regcred
